[bar]
height = 24
icon_size = 24
layer = "top"
homogenous = true
threaded = false
position = "bottom"
gaps = [8, 8, 8, 8]

[icons]
cpu = "theme://cpu.svg"
memory = "theme://memory.svg"
clock = "theme://clock"
therm = "theme://temperature.svg"


[start.temperature]
interval = 1
type = "temperature"
ramp = [
    "A [icon=level1;]",
    "B [icon=level2;classes:icon=therm;]",
    "C [icon=level3;classes:icon=therm;]",
    "D [icon=level4;classes:icon=therm;]"]
label_format = "[icon=therm<;]{ramp} {temp}°C"


# [start.cpu]
# type = "cpu_usage"
# interval = 10
# label_format = "[icon=cpu<;]{percent}%"


# [start.disk]
# type = "disk"
# interval = 10
# label_format = "[icon=disk<;]{percent}%"


# [start.memory]
# type = "memory"
# interval = 10
# label_format = "mem {percent}%"
# # [center.exec_one_tail]
# # type = "exec_tail"
# # label_format = "({label}) <{ramp}>"
# # ramp = ["a", "b", "c", "D"]
# # cmdline = [
# #     "/home/meh/test.sh",
# # ]

# [end.kb]
# type = "i3_kblayout"
# label_format = "{layout}"
# rewrite = {
#     "(?i)english.*" = "GB",
#     "(?i)ukrainian.*" = "UA",
#     "(?i)german.*" = "DE",
# }

# [end.datetime]
# type = "datetime"
# interval = 5
# label_format = "{datetime:%H:%M:%S}"
# # [end.wlan]
# # type = "wifi"
# # iface = "wlan0"
# # ramp = [
# #     "󰤮",
# #     "󰤟",
# #     "󰤥",
# #     "󰤨",
# # ]
# # backend = "iwd"
# # label_format = "{ramp} {ssid} {percentage}%"

# # [end.vol]
# # type = "pulse_volume"
# # onclick = ["firefox"]
# # ramp = [
# #     "󰝟",
# #     "󰕿",
# #     "󰖀",
# #     "󰖀",
# #     "󰕾",
# # ]
# # label_format = "{ramp} {percent}%"


# # [start.file_w]
# # type = "file"
# # path = "/home/meh/lines.txt"
# # label_format = "FILE: {label}"
